### ISSUE TITLE
All the icons dired is broken after upgrading to Emacs 25.3.1

### ISSUE THREAD

**Issue by justinjk007** [jtbm37/all-the-icons-dired#12]
Hello there,

I opened the issue [here](https://github.com/domtronn/all-the-icons.el/issues/85) and @domtronn found out that the fonts being broken is an issue with this mode and not the fonts or the main mode itself.

Can you figure what it is making dired icons and look like this.

![output](https://user-images.githubusercontent.com/12916795/31279354-c6f06a7e-aa76-11e7-9a16-9bd617e3331f.PNG)

I am on windows 10 with emacs 25.3.1 using 20170418.143 version of the mode.

**Comment by jtbm37** [comment]
Thanks for reporting this.

I am on GNU Emacs 26.0.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9). It works fine.

**Comment by justinjk007** [comment]
So the option is to upgrade to 26 ?

**Comment by justinjk007** [comment]
I updated emacs to the 64 bit version , bammm no more problemo!!
