### ISSUE TITLE
Icons sizing and accuracy 

### ISSUE THREAD

**Issue by dchrzanowski** [jtbm37/all-the-icons-dired#16]
Just did a fresh reinstall of emacs (old was fine in terms of icons). 

The new installation has odd icons for files (Vue icon for js files, warning for Download, a Peach for .elc files, etc), and icons display no colours, also some files display huge icons as well. What could be wrong? I might point out that neotree's icons are coloured, are of the right type and size.

EDIT:
[All the icons config](https://github.com/Grimscythe1983/.emacs.d/blob/e8ce72c83a214d21681a88cb5aeebeeec2861741/setup-files/navigation-setup.el#L153)
[Dired config](https://github.com/Grimscythe1983/.emacs.d/blob/master/setup-files/dired-settings-setup.el)

**Comment by nandryshak** [comment]
See: https://github.com/domtronn/all-the-icons.el/pull/106

**Comment by dchrzanowski** [comment]
This surely did the trick for `dired`. Thank you very much for this.

Now I just have to figure out why the fonts display incorrectly in `prog-mode` buffers.
