### ISSUE TITLE
This breaks wdired-mode

### ISSUE THREAD

**Issue by terlar** [jtbm37/all-the-icons-dired#18]
When running `wdired-change-to-wdired-mode` and try to rename a file for example. The icon will be part of the file name and it will fail to rename the file.

I wonder if it is possible to put a hook that disables this inside wdired-mode or optimally if the icons could be omitted from the wdired logic, but that might be a tricky thing to do.

**Comment by jtbm37** [comment]
Thanks for submitting this issue.
Are you sure you don't have some custom changes that interfer with this mode ?
I can use wdired mode without any issues.

**Comment by terlar** [comment]
Hmm, you seem to be right, I will do some further investigation...
Thank you for the feedback.

**Comment by terlar** [comment]
This seems to be a regression between emacs 27 (HEAD) and emacs 26. It works in emacs 26 but not in emacs 27.

With following Emacs version:
```
GNU Emacs 27.0.50 (build 2, x86_64-apple-darwin18.2.0, NS appkit-1671.10 Version 10.14.1 (Build 18B75)) of 2018-12-02
```

Steps to reproduce:
```
M-: (require 'all-the-icons-dired)
C-x C-f /tmp
M-x all-the-icons-dired
M-x wdired-change-to-wdired-mode
* change name of some file *
C-c C-c
```

When doing this I receive:
```
Tue Dec  4 12:38:19 2018	Buffer ‘tmp’

Rename ‘/tmp/ test-file’ to ‘/tmp/ test-abc-file’ failed:
(file-missing Renaming No such file or directory /tmp/ test-file /tmp/ test-abc-file)

1 rename actions failed
```

The icons are included within the name.

**Comment by jtbm37** [comment]
Well done figuring this out.

Now we'd need to investigate what has changed and then whether this is a change that needs to be done in this mode or in the `all-the-icons`'.

**Comment by JSpenced** [comment]
Was this figured out?? I also have the problem if I use the tag "--classify " or "-F" in the dired-actual-switches. The rename doesn't work because it takes that as part of the filename so it thinks you are trying to move every directory inside it self due to directories ending with `/`.

Not sure if this happened before but also when upgrading to head to get magit working again I noticed this. I don't use wdired often so might have also been the case on emacs 26.1.

**Comment by jave** [comment]
I also experience this problem

**Comment by terlar** [comment]
I am still using my patched version:
https://github.com/jtbm37/all-the-icons-dired/pull/19

So you could give that a try if you want.

**Comment by JSpenced** [comment]
Yeah, I wrote a custom defadvice that did something similar to remove --classify tags from dired switches. Also, I submitted a bug report to the emacs mailing list.

**Comment by conao3** [comment]
#24 might helps this issue. This issue still remained?

**Comment by noctuid** [comment]
No, this issue seems to be fixed.
