### ISSUE TITLE
does not work with dired-subtree

### ISSUE THREAD

**Issue by yilkalargaw** [jtbm37/all-the-icons-dired#22]
I am having trouble getting the all-the-icons-dired to work with dired-subtree. The main directory has icons but the subtree will not render any icons. I would appreciate any help.

**Comment by mtekman** [comment]
```
(use-package all-the-icons-dired
  :after all-the-icons
  :hook dired)
```
and 

```
(use-package dired-sidebar
  :bind (("C-x C-n" . dired-sidebar-toggle-sidebar))
  :ensure t
  :commands (dired-sidebar-toggle-sidebar)
  :init
  (add-hook 'dired-sidebar-mode-hook
            (lambda ()
              (unless (file-remote-p default-directory)
                (auto-revert-mode))))
  :config
  (push 'toggle-window-split dired-sidebar-toggle-hidden-commands)
  (push 'rotate-windows dired-sidebar-toggle-hidden-commands)
  (setq dired-sidebar-subtree-line-prefix "__")
  (setq dired-sidebar-theme 'icons)
  (setq dired-sidebar-use-term-integration t)
  (setq dired-sidebar-use-custom-font t))
```
(make sure you set dired-sidebar-theme to `icons`)

**Comment by yilkalargaw** [comment]
I used the config you provided but still the subdirectories listed by dired-subtree don't have icons rendered for them.

**Comment by mtekman** [comment]
I updated the config, please try it again and let me know if it works.

**Comment by yilkalargaw** [comment]
I tried the config with the slight modification of using ```hook (dired-mode . all-the-icons-dired-mode)``` instead of ```:hook dired. The reasult is the same all the items in the top directory have icons but those in the subtree show up without  an icon in the main dired buffer. In dired-sidebar items in the sub tree listing also have icons rendered for them and I want my main dired buffer to have a similar behavior.

**Comment by mtekman** [comment]
that's really strange. What version of emacs are using? I am `27.0.50`

**Comment by yilkalargaw** [comment]
Finally figured out the issue. The icons will be displayed if  you do revert-buffer(g) after listing subtrees with dired-subtree(tab). I am wondering if it is programmatically possible to revert buffer after every dired-subtree listing. I am willing to help.

**Comment by Kungsgeten** [comment]
I also had this problem and found the following solution. Don't know if its the best way to do it, since it sometimes show details of the subtree even if I have that turned off. Anyway:

```
(with-eval-after-load 'all-the-icons-dired
    (defun ess/dired-subtree-icons ()
      (dired-subtree-down)
      (dired-subtree-narrow)
      (when (fboundp 'dired-insert-set-properties)
        (let ((inhibit-read-only t)
              (ov (dired-subtree--get-ov)))
          (dired-insert-set-properties (overlay-start ov) (overlay-end ov))))
      (all-the-icons-dired--reset)
      (all-the-icons-dired--display)
      (widen))

    (remove-hook 'dired-subtree-after-insert-hook 'dired-subtree--after-insert)
    (add-hook 'dired-subtree-after-insert-hook 'ess/dired-subtree-icons))
```

Also a shoutout to @Fuco1 if he has any ideas.

**Comment by Fuco1** [comment]
I can't say much without seeing how this package here works, but if the solution of @Kungsgeten works I have no problem adding this directly into the package so it just works out of the box (with a proper feature check of course).

**Comment by mohkale** [comment]
If anyones having the same issue with `dired-insert-subdir` instead of `dired-subtree-insert` (which is from the [dired-hacks](https://github.com/Fuco1/dired-hacks) library BTW), I've adapted @Kungsgeten 's solution to work with that as well. You have to do a little extra work because `dired-insert-subdir` doesn't provide an after hook, but I've gotten this working for myself.

```elisp
(defvar dired-subdir-after-insert-hook nil
  "hook which is run after dired inserts a subtree.")

(advice-add 'dired-insert-subdir
            :after
            (defun dired-insert-subdir--run-hook+ (&rest _)
              (run-hook-with-args 'dired-subdir-after-insert-hook)))

(defun all-the-icons-dired--subdir-icons+ ()
  "insert icons for subdirectories in dired sessions."
  (save-excursion
    (unwind-protect
        (progn
          (narrow-to-region
           (line-beginning-position)
           (condition-case nil
               (dired-next-subdir 1)
             (error (point-max))))
          (all-the-icons-dired--reset)
          (all-the-icons-dired--display))
      (widen))))

(add-hook 'dired-subdir-after-insert-hook 'all-the-icons-dired--subdir-icons+)
```

**Comment by yilkalargaw** [comment]
For emacs27 the issue is not present but for emacs 26 adding the following advice corrected every thing for me.

```elisp
  (defadvice dired-subtree-toggle (after dired-icons-refreash ())
    "Insert an empty line when moving up from the top line."
    (let ((dafile "~/.emacs.d/custom_faces.el"))		     
      (revert-buffer)))

  (ad-activate 'dired-subtree-toggle)

```
