### ISSUE TITLE
Icons are not aligned

### ISSUE THREAD

**Issue by conao3** [jtbm37/all-the-icons-dired#29]
Hi!
I found icons inserted by this package are not aligned in some directories.
## screenshot
Emacs source directory, for example
![Screenshot_2020-01-25_12-08-44](https://user-images.githubusercontent.com/4703128/73115691-eccb8480-3f6c-11ea-92ab-42d09d47b6c0.png)

**Comment by fpopineau** [comment]
Hi,

It has been investigated here https://github.com/domtronn/all-the-icons.el/issues/82#issuecomment-516511749 . And the fix is working.

Regards,

**Comment by conao3** [comment]
This issue had solved by #31.
