### ISSUE TITLE
Icons not colored

### ISSUE THREAD

**Issue by iris-garcia** [jtbm37/all-the-icons-dired#54]
Not sure if this is because of an update in `all-the-icons` package, but I don't see colored icons anymore in dired.

![image](https://user-images.githubusercontent.com/3024945/108839048-cc895180-75d4-11eb-9e4d-73bf7d3ef0e7.png)

**Comment by iris-garcia** [comment]
Just found the variable `all-the-icons-dired-monochrome` sorry...

**Comment by saerosV** [comment]
For anyone using Doom Emacs who comes across this "problem" in the future, go to `~/.emacs.d/modules/emacs/dired/config.el` search for the `(use-package! all-the-icons-dired ...)` macro, and add  `(setq all-the-icons-dired-monochrome nil)` to your `:init` symbol. 
If you don't have it, just create one. 

It should look like this:
```

(use-package! all-the-icons-dired
  :when (featurep! +icons)
  :hook (dired-mode . all-the-icons-dired-mode)
  :init (setq all-the-icons-dired-monochrome nil)
  ...)
```
