### ISSUE TITLE
setq: Wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by alexei-28** [jtbm37/all-the-icons-dired#56]
Linux Mint 20
Emacs 27.2

packages: all-the-icons, all-the-icons-cadidates, all-the-icons-dired

In my init file

`(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)
`
But when I try to open folder in dired mode, I get error:
`
setq: Wrong type argument: number-or-marker-p, nil`

**Comment by Myzel394** [comment]
Were you able to find a fix for this?
